image: node:10.1.0

pipelines:
  master:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm test
          - npm test-lint
          - npm test-coverage
